Home/urls.py
from django.urls import include, path
from .views import Home,Dicas,Assuntos,cronometro
from ProvaAntiga.views import homeProva
from CalcularNotas.views import homeNotas
from Redações.views import homeRedacoes
from authors import views

app_name = 'home'

urlpatterns = [
    path('', Home,name="Home"),
    path('Prova/', homeProva,name='prova'),
    path('Notas/', homeNotas,name='notas'),
    path('cronometro/', cronometro,name='cronometro'),
    path('Dicas/', Dicas,name='Dicas'),
    path('Assuntos/', Assuntos,name='Assuntos'),
    path('Redacoes/', homeRedacoes,name='Redacoes'),
    path('login/', views.login_view, name='login'),
    
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls'),name='index'),
    path('Prova/', include('ProvaAntiga.urls')),
    path('login/', include('authors.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):

    return render(request, 'Home/home.html')

def Dicas(request):

    return render(request, 'Home/Dicas.html')

def Assuntos(request):

    return render(request, 'Home/Assuntos.html')

def cronometro(request):

    return render(request, 'Home/cronometro.html')

Home/templates/Home/Assuntos.html
{% extends 'global/base.html' %}

{% block title %}Assuntos | {% endblock title %}

{% block content %}

{% include 'global/partials/messages.html' %}
<br/>
<br/>
<br/>

<header>
    <h1>Sumário dos Tópicos mais Relevantes no ENEM</h1>
</header>

<ul class="disciplinas">
    <li class="disciplina">Linguagens, Códigos e suas Tecnologias
        <h4>Português e Literatura</h4>
        <ul class="itens">
            <li>Interpretação de textos (33,3%)</li>
            <li>Tendências contemporâneas (28%)</li>
            <li>Estrutura e formação das palavras (21%)</li>
            <li>Tipos de texto (19%)</li>
            <li>Análise da pessoa, do espaço e do tempo (14%)</li>
            <li>Funções da linguagem (13%)</li>
            <li>Pontuação (10%)</li>
            <li>Narratividade (9%)</li>
            <li>Literatura (7,8%)</li>
            <li>Classe de palavras (7%)</li>
            <li>Verbo (7%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Inglês</h4>
        <ul class="itens">
            <li>Interpretação de Textos (51,3%)</li>
            <li>Domínio Lexical (14,8%)</li>
            <li>Identificação de Função do Texto (6,1%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Espanhol</h4>
        <ul class="itens">
            <li>Interpretação de Textos (52,2%)</li>
            <li>Domínio Lexical (14,8%)</li>
            <li>Identificação de Função do Texto (6,1%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Artes</h4>
        <ul class="itens">
            <li>Arte Contemporânea (60%)</li>
            <li>Arte nos séculos XV e XVI (10%)</li>
            <li>Elementos básicos das Artes Plásticas (10%)</li>
            <li>Elementos básicos de Música (10%)</li>
            <li>Música no século XX (5%)</li>
        </ul>
    </li>
</ul>

<ul class="disciplinas">
    <li class="disciplina">Ciências Humanas e suas Tecnologias
        <h4>História</h4>
        <ul class="itens">
            <li>Idade Contemporânea (17,7%)</li>
            <li>2ª Guerra Mundial e suas consequências (13,6%)</li>
            <li>Brasil Colônia (12,7%)</li>
            <li>Primeiro e Segundo Reinado (12,3%)</li>
            <li>Governos pós-regime militar - Redemocratização (12,3%)</li>
            <li>Era Vargas (11,1%)</li>
            <li>História Política (10,5%)</li>
            <li>República Velha (9,9%)</li>
            <li>Patrimônio Histórico-Cultural e Memória (7,8%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Geografia</h4>
        <ul class="itens">
            <li>Geografia Agrária (18,1%)</li>
            <li>Questões Ambientais (15,5%)</li>
            <li>Geografia Física (10,9%)</li>
            <li>Geografia Urbana (10,4%)</li>
            <li>Climatologia (10,4%)</li>
            <li>Urbanização (10,4%)</li>
            <li>Globalização (9,1%)</li>
            <li>Cartografia (6,5%)</li>
            <li>Indústria (6,5%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Filosofia</h4>
        <ul class="itens">
            <li>Aristóteles e escola helenística (18,8%)</li>
            <li>Ética e Justiça (18,7%)</li>
            <li>Racionalismo moderno (18,8%)</li>
            <li>Filosofia Antiga (16,8%)</li>
            <li>Escola sofística, Sócrates e Platão (12,5%)</li>
            <li>Filosofia Contemporânea (12,4%)</li>
            <li>Filosofia Moderna (11,6%)</li>
            <li>Escola de Frankfurt (9,4%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Sociologia</h4>
        <ul class="itens">
            <li>Sociologia contemporânea (28,6%)</li>
            <li>Mundo do Trabalho (21,9%)</li>
            <li>Cultura e Indústria Cultural (12,9%)</li>
            <li>Ideologia (11,6%)</li>
            <li>Meios de Comunicação, Tecnologia e Cultura de Massa (11,6%)</li>
            <li>Cidadania (10,3%)</li>
            <li>Capitalismo (7,1%)</li>
            <li>Economia e sociedade (7,1%)</li>
        </ul>
    </li>
</ul>

<ul class="disciplinas">
    <li class="disciplina">Ciências da Natureza e suas Tecnologias
        <h4>Química</h4>
        <ul class="itens">
            <li>Físico-Química (27,0%)</li>
            <li>Química Geral (26,8%)</li>
            <li>Química Orgânica (19,2%)</li>
            <li>Ligações químicas, polaridade e forças (13,4%)</li>
            <li>Reações orgânicas (11%)</li>
            <li>Compostos orgânicos (9,8%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Física</h4>
        <ul class="itens">
            <li>Mecânica (30,9%)</li>
            <li>Eletricidade e Energia (25,8%)</li>
            <li>Ondulatória (18%)</li>
            <li>Termologia (17,1%)</li>
            <li>Acústica (11%)</li>
            <li>Energia, trabalho e potência (8,2%)</li>
            <li>Resistores (8,2%)</li>
            <li>Calorimetria (5,5%)</li>
            <li>Impulso, quantidade de movimento e análise dimensional (5,5%)</li>
            <li>Introdução à óptica geométrica (5,5%)</li>
        </ul>
    </li>
    <li class="disciplina">
        <h4>Biologia</h4>
        <ul class="itens">
            <li>Humanidade e Ambiente (19,5%)</li>
            <li>Citologia (11,5%)</li>
            <li>Histologia e Fisiologia (11,5%)</li>
            <li>Sistema imunológico (9,9%)</li>
            <li>Ecossistemas (8,5%)</li>
            <li>Fundamentos da ecologia (8,3%)</li>
            <li>Biotecnologia (8,1%)</li>
            <li>DNA e RNA (5,6%)</li>
            <li>Genética (5,6%)</li>
        </ul>
    </li>
</ul>

<ul class="disciplinas">
    <li class="disciplina">Matemática e suas Tecnologias
        <h4>Matemática</h4>
        <ul class="itens">
            <li>Geometria (22,5%)</li>
            <li>Equação do Primeiro Grau e Equação do Segundo Grau (17%)</li>
            <li>Escalas, Razão e Proporção (14,2%)</li>
            <li>Grandezas proporcionais e médias algébricas (14%)</li>
            <li>Aritmética (11,8%)</li>
            <li>Porcentagem e matemática financeira (11%)</li>
            <li>Gráficos e Tabelas (9,1%)</li>
            <li>Funções (8,7%)</li>
            <li>Noções básicas de estatística (6%)</li>
            <li>Probabilidade (6%)</li>
            <li>Área de figuras planas e Área dos polígonos (5%)</li>
        </ul>
    </li>
        <ul class="disciplinas"></ul>
        <li class="disciplina">
            
            <h4>Dicas de Youtubers:</h4>
            <div class="dicas">
            <a href="https://www.youtube.com/@ProfessorNoslen">Linguagens</a><br>
            <a href="https://www.youtube.com/@professorferretto">Matemática</a><br>
            <a href="https://www.youtube.com/@paulojubilut">Biologia</a><br>
            <a href="https://www.youtube.com/@professorboaro">Química</a><br>
            <a href="https://www.youtube.com/@Fisica2.0">Fisica</a>
            <h4>Dicas de cursinhos:</h4>
            <a href="https://www.proenem.com.br/">PROENEM</a><br>
            <a href="https://descomplica.com.br/super-aulao-enem?utm_source=google&utm_medium=cpc&utm_campaign=google_psq_uee_awareness_gwt-paid-media_topo_conversao_retafinal23_lead_marktech&utm_term=assuntos%20que%20mais%20caem%20no%20enem&utm_content=reta_final&gclid=Cj0KCQjwhfipBhCqARIsAH9msbkTO4YDpW434PG9LPvWjP_RgUlrw9sh4hF8WcvgIP-tAuj-N3HU2dwaAoF7EALw_wcB">DESCOMPLICA</a><br>
            <a href="https://www.mesalva.com/app/banco-de-provas/provas-anteriores-enem">MESALVA (OBS:esse site também contém todos as edições das provas anteriores para você baixar e treinar)</a>
</div>
</li>
</ul>

</div>
{% endblock content %}

Home/templates/Home/Dicas.html
{% extends 'global/base.html' %}

{% block title %}Dicas | {% endblock title %}

{% block content %}

{% include 'global/partials/messages.html' %}
<br/>
<br/>
<br/>
<div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          <h1 class="introducao">Instruções para a Redação do Enem</h1>
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body"><section id="introducao">
            <p>A redação do Enem é uma parte importante do exame e exige atenção especial. Abaixo, você encontrará instruções e dicas para escrever uma redação eficaz.</p>
        </section>

        <section>
            <h2 id="subtitulo">Estrutura da Redação</h2>
            <p>A redação do Enem geralmente segue a estrutura de um texto dissertativo-argumentativo. Ela deve conter introdução, desenvolvimento e conclusão. A introdução apresenta o tema e a tese, o desenvolvimento argumenta a favor da tese e a conclusão retoma os principais pontos e apresenta uma proposta de intervenção.</p>
        </section></div>
      </div>
    </div>
        <div class="container">
            <section>
                <h2 id="subtitulo">Competências Avaliadas</h2>
                <p class="paragrafo">A redação do Enem é avaliada com base em cinco competências:</p>
                <div class="row">
                    <!-- Duas colunas de um lado -->
                    <div class="col-md-4">
                      <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Competência 1</h5>
                          <p class="card-text">Demonstrar domínio da norma culta da língua escrita.</p>
                        </div>
                      </div>
                    </div>
                    
                    <div class="col-md-4">
                      <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Competência 2</h5>
                          <p class="card-text">Compreender a proposta de redação e aplicar conceitos das várias áreas de conhecimento para desenvolver o tema, dentro dos limites estruturais do texto dissertativo-argumentativo em prosa.</p>
                        </div>
                      </div>
                    </div>
                  
                    <!-- Uma coluna no meio -->
                    <div class="col-md-4">
                      <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Competência 5</h5>
                          <p class="card-text">Elaborar proposta de intervenção para o problema abordado, respeitando os direitos humanos.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div class="row">
                    <!-- Duas colunas do outro lado -->
                    <div class="col-md-6">
                      <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Competência 3</h5>
                          <p class="card-text">Selecionar, relacionar, organizar e interpretar informações, fatos, opiniões e argumentos em defesa de um ponto de vista.</p>
                        </div>
                      </div>
                    </div>
                    
                    <div class="col-md-6">
                      <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">Competência 4</h5>
                          <p class="card-text">Demonstrar conhecimento dos mecanismos linguísticos necessários para a construção da argumentação.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
            </section>
            <br>
                <h2 id="subtitulo">Estratégias de Abordagem</h2>
                <p class="paragrafo">Para escrever uma redação eficaz, siga estas estratégias:</p>
                <ul class="listname">
                    <li>Leia cuidadosamente a proposta de redação e entenda o que é solicitado.</li>
                    <br>
                    <li>Organize suas ideias antes de começar a escrever, criando um esboço do seu texto.</li>
                    <br>
                    <li>Use argumentos consistentes e dados relevantes para sustentar sua tese.</li>
                    <br>
                    <li>Mantenha uma linguagem clara e objetiva.</li>
                    <br>
                    <li>Revise e corrija seu texto, verificando erros gramaticais e de ortografia.</li>
                </ul>
                <br><br>
            </section>
           

</div>
</div>









{% endblock content %}

Home/templates/Home/cronometro.html
{% extends 'global/base.html' %}

{% block title %}cro | {% endblock title %}

{% block content %}
<br><br>
<br><br>
    <div class="message">
        <p>Explore o poder do tempo dedicado ao estudo e veja suas habilidades e conhecimentos expandirem. Cada segundo conta, cada minuto é uma oportunidade para se aproximar dos seus objetivos educacionais. Aproveite esta jornada de aprendizado e transforme o tempo em uma ferramenta valiosa para o seu sucesso! 📚🕒✨</p>
    </div>
    <div class="card1">
        <h1>Cronômetro</h1>
        <div id="cronometro">00:00:00</div>
        <button onclick="iniciarCronometro()">Iniciar</button>
        <button onclick="pausarCronometro()">Pausar</button>
        <button onclick="zerarCronometro()">Zerar</button>
        <div id="mensagem"></div>
    </div>

    <script>
        let tempoAtual = 0;
        let cronometro;

        function iniciarCronometro() {
            cronometro = setInterval(() => {
                tempoAtual++;
                exibirTempo();
                salvarTempo();
            }, 1000);
        }

        function pausarCronometro() {
            clearInterval(cronometro);
            salvarTempo();
            exibirMensagem();
        }

        function zerarCronometro() {
            tempoAtual = 0;
            exibirTempo();
            salvarTempo();
        }

        function exibirTempo() {
            const horas = Math.floor(tempoAtual / 3600);
            const minutos = Math.floor((tempoAtual % 3600) / 60);
            const segundos = tempoAtual % 60;
            document.getElementById('cronometro').innerText = `${formatarNumero(horas)}:${formatarNumero(minutos)}:${formatarNumero(segundos)}`;
        }

        function formatarNumero(numero) {
            return numero < 10 ? `0${numero}` : numero;
        }

        function salvarTempo() {
            localStorage.setItem('tempoSalvo', tempoAtual);
        }

        function carregarTempoSalvo() {
            const tempoSalvo = localStorage.getItem('tempoSalvo');
            if (tempoSalvo !== null) {
                tempoAtual = parseInt(tempoSalvo);
                iniciarCronometro(); // Continua o cronômetro quando a página é carregada
            }
        }

        function exibirMensagem() {
            const minutosEstudados = Math.floor(tempoAtual / 60);
            const mensagem = `Você estudou por ${minutosEstudados} minutos. Parabéns!`;
            document.getElementById('mensagem').innerText = mensagem;
        }

        // Carregar tempo salvo ao iniciar a página
        carregarTempoSalvo();
    </script>


{% endblock content %}

Home/templates/Home/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}

{% include 'global/partials/messages.html' %}
<br/>
<main class="container mt-5 text-center">
    <h1>Bem-vindo à sua Jornada para o Sucesso no ENEM!</h1>
    <p>Este é o seu ponto de partida para uma preparação sólida e eficaz no ENEM. Aqui, você terá acesso a ferramentas para calcular sua nota, valiosas dicas de cursinhos e a conveniência de baixar folhas de redação em PDF para aprimorar suas habilidades e atingir o seu melhor desempenho no Exame Nacional do Ensino Médio.</p>
    <p class="inicio">Prepare-se, vamos começar!</p>
</main>

<section class="container text-center mt-4">
    <a class="btn btn-primary" href="{%url 'home:Assuntos'%}">ACESSE AQUI E CONFIRA OS ASSUNTOS QUE MAIS CAEM <br>NO ENEM E DICAS DE CURSINHOS PARA CADA ÁREA DE CONHECIMENTO</a>
</section>
<br>

<div class="d-flex justify-content-center">
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner" style="max-height: 300px; width: 500px;">
            <div class="carousel-item active" data-bs-interval="10000">
                <img src="https://raw.githubusercontent.com/tgn76ok/img2/main/calc.jpg" class="d-block w-100" alt="Imagem 1">
                <div class="carousel-caption d-none d-md-block">
                    <p> Cada momento dedicado aos estudos é um investimento no seu futuro acadêmico.</p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
                <img src="https://raw.githubusercontent.com/tgn76ok/img2/main/livros.jpg" class="d-block w-100" alt="Imagem 2">
                <div class="carousel-caption d-none d-md-block">
                    <p>A dedicação à leitura expande horizontes - explore diferentes temas para enriquecer seu conhecimento.</p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
                <img src="https://raw.githubusercontent.com/tgn76ok/img2/main/maolivro.jpg" class="d-block w-100" alt="Imagem 3">
                <div class="carousel-caption d-none d-md-block">
                    <p> Aqui, você pode calcular suas notas e planejar sua jornada para o sucesso.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
            <span class="carousel-control-next-icon" ariahidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
{% endblock content %}

{% include 'global/partials/footer.html' %}