CalcularNotas/urls.py
from django.urls import path

from . import views

app_name = 'Notas'

urlpatterns = [
    path('', views.homeProva, name="homev"),
    # path('Prova/search/', views.search, name="search"),
    # path('Prova/category/<int:category_id>/',
    #      views.category, name="category"),
    
]

Home/urls.py
from django.urls import include, path
from .views import Home,Dicas,Assuntos,cronometro
from ProvaAntiga.views import homeProva
from CalcularNotas.views import homeNotas
from Redações.views import homeRedacoes
from authors import views

app_name = 'home'

urlpatterns = [
    path('', Home,name="Home"),
    path('Prova/', homeProva,name='prova'),
    path('Notas/', homeNotas,name='notas'),
    path('cronometro/', cronometro,name='cronometro'),
    path('Dicas/', Dicas,name='Dicas'),
    path('Assuntos/', Assuntos,name='Assuntos'),
    path('Redacoes/', homeRedacoes,name='Redacoes'),
    path('login/', views.login_view, name='login'),
    
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls'),name='index'),
    path('Prova/', include('ProvaAntiga.urls')),
    path('login/', include('authors.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CalcularNotas/views.py
from django.shortcuts import render

# Create your views here.
def homeNotas(request):
    print(request.POST)
    mensagens = ''
    contex = {}
    
    if request.method == "POST":
        lingua = request.POST['Nota1']
        Natureza = request.POST['Nota2']
        Humanas = request.POST['Nota3']
        tecnologias = request.POST['Nota4']
        Redação = request.POST['Nota5']
        
        mensagens = list()
        if lingua == '' and lingua: lingua = 0
        if Natureza == '' and Natureza: Natureza = 0
        if Humanas == '' and Humanas: Humanas = 0
        if tecnologias == '' and tecnologias: tecnologias = 0
        if Redação == '' and Redação: Redação = 0
        
        is_invalido = (
            (int(lingua) < 1000) and (int(Natureza) < 1000) and (int(Humanas) < 1000) and (int(tecnologias) < 1000) and (int(Redação) < 1000) 
             )
        if not is_invalido:
            mensagens.append( 'valor invalido')
            contex = {
                 "messages":mensagens
                 }
        else:
            valor = (int(lingua) + int(Natureza) + int(Humanas) + int(tecnologias) + int(Redação) ) /5
            contex = {
                "messages":mensagens,
                "valor":int(valor)
            }
            
        
        
    
    
    return render(request, 'CalcularNotas/home.html',context=contex)

Home/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):

    return render(request, 'Home/home.html')

def Dicas(request):

    return render(request, 'Home/Dicas.html')

def Assuntos(request):

    return render(request, 'Home/Assuntos.html')

def cronometro(request):

    return render(request, 'Home/cronometro.html')

CalcularNotas/templates/CalcularNotas/home.html
{% extends 'global/base.html' %}

{% block title %}Notas| {% endblock title %}

{% block content %}
<!-- {% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
    <div class="message {{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %} -->
<div class="mainNotas">

    <div class="notas">
        <h1>Simule sua nota:</h1>
        <br>
        <form action="{% url 'home:notas' %}" method="POST" id="notaForm">
            {% csrf_token %}
            <label for="Nota1">Sua nota em Linguagens, Códigos e suas Tecnologias:</label>
            <input id="inputNo" type="number" name="Nota1"><br><br>
            <label for="Nota2">Sua nota em Ciências da Natureza:</label>
            <input id="inputNo" type="number" name="Nota2"><br><br>
            <label for="Nota3">Sua nota em Ciências Humanas:</label>
            <input id="inputNo" type="number" name="Nota3"><br><br>
            <label for="Nota4">Matemática e suas tecnologias:</label>
            <input id="inputNo" type="number" name="Nota4"><br><br>
            <label for="Nota5">Sua nota em Redação:</label>
            <input id="inputNo" type="number" name="Nota5"><br><br>
            <button type="submit" id="calcularButton">Calcular Nota</button>
            <div id="resultado" class="resultado"></div>

        </form>
        {% if valor %}
        <br>
        <div class="main-content center container messages-container">
            <h2>
                Sua nota média: {{valor}}
            </h2>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}