Home/urls.py
from django.urls import include, path
from .views import Home,Dicas,Assuntos,cronometro
from ProvaAntiga.views import homeProva
from CalcularNotas.views import homeNotas
from Redações.views import homeRedacoes
from authors import views

app_name = 'home'

urlpatterns = [
    path('', Home,name="Home"),
    path('Prova/', homeProva,name='prova'),
    path('Notas/', homeNotas,name='notas'),
    path('cronometro/', cronometro,name='cronometro'),
    path('Dicas/', Dicas,name='Dicas'),
    path('Assuntos/', Assuntos,name='Assuntos'),
    path('Redacoes/', homeRedacoes,name='Redacoes'),
    path('login/', views.login_view, name='login'),
    
]

ProvaAntiga/urls.py
from django.urls import path

from . import views

app_name = 'provas'

urlpatterns = [
    path('', views.homeProva, name="homev"),
    # path('Prova/search/', views.search, name="search"),
    # path('Prova/category/<int:category_id>/',
    #      views.category, name="category"),
    path('Detalhe/<int:id>/', views.getprova, name="Prova"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls'),name='index'),
    path('Prova/', include('ProvaAntiga.urls')),
    path('login/', include('authors.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ProvaAntiga/models.py
from django.db import models

# Create your models here.
 
def pdf_upload_path(instance, filename):
    return f'Media/{instance.created_date.strftime("%Y-%m-%d")}_test_{filename}'
class File(models.Model):
    
    pdf = models.FileField(upload_to='Midia/%Y/%m/%d', blank=True)
    name = models.CharField(max_length=250)
    def __str__(self):
        return self.name


class Prova(models.Model):
    name = models.CharField(max_length=250)
    
    files = models.ManyToManyField(File, verbose_name="pdfs")
    ano = models.IntegerField()
    
    def __str__(self):
        return self.name

Home/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):

    return render(request, 'Home/home.html')

def Dicas(request):

    return render(request, 'Home/Dicas.html')

def Assuntos(request):

    return render(request, 'Home/Assuntos.html')

def cronometro(request):

    return render(request, 'Home/cronometro.html')

ProvaAntiga/views.py
from .models import Prova
from django.shortcuts import get_list_or_404, get_object_or_404, render

from django.urls import reverse


# Create your views here.
def homeProva(request):
    prova = Prova.objects.all()

    

    return render(request, 'Prova/home.html', context={
        'provas': prova,
    })

def getprova(request, id):
    Provau = get_object_or_404(Prova, pk=id)
    arquivos = Provau.files.values()
    
    url = reverse('home:Home')
    url = url + 'media/'
    print(url)

    return render(request, 'Prova/Prova-view.html', context={
        'provas': Provau,
        'arquivos':arquivos,
        'url_pdf':url
    })

ProvaAntiga/templates/Prova/Prova-view.html
{% extends 'global/base.html' %}

{% block title %}{{ provas.name }} | {% endblock title %}

{% block content %}
<br />
<br />
<br />
<h2 class="TypeProvasT">

    {{provas.name}}
</h2>
<div class="TypeProvas">
    {% for arquivo in arquivos %}
    <div class="TypeProva">

        <p> {{arquivo.name}} </p>
        <a href="{{url_pdf}}{{arquivo.pdf}}" target="_blank" rel="noopener noreferrer"> Ver</a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

http://127.0.0.1:8000/media/{{arquivo.pdf}}

ProvaAntiga/templates/Prova/home.html
{% extends 'global/base.html' %}

{% block title %}Provas | {% endblock title %}

{% block content %}

<br />
<br />
<br />

<section id="download">
    {% for prova in provas %}
    <!-- {{prova.name}} -->
    <a class="itensProva" href="{% url 'provas:Prova' prova.id %}">
        {{prova.name}}
    </a>


    {% endfor %}
</section>
{% endblock content %}